### PR TITLE
Pulling protobuf-csharp-port into csharp/ directory

### PR DESCRIPTION
**Pull request by jtattermusch**
Imported code from https://github.com/jskeet/protobuf-csharp-port and merged into csharp/ subtree.
All the history should be there (history was rewritten to link authors to their github account - allows googlebot to check CLA presence).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@anandolee please take a look as well.

**Comment by jtattermusch** [comment]
As you can see in the commit history, some users are not correctly linked to their github accounts.
For example rogerk appears as "rogerk@localhost". It would be nice to at least try to link commits to github accounts of their real authors.

I've found that rogerk is csharptest on github - https://github.com/csharptest
I think what we need to do to properly link authors is to change commit info to their real e-mail. Jon, can you send me those (in case they are different e-mails than what I have)?

**Comment by jskeet** [comment]
Have mailed Jan the email address of Roger, although we'll need to confirm he's happy for that to appear in the logs.

**Comment by jskeet** [comment]
Am I right in saying the plan is to commit everything from the "old" repo, including ProtoGen - and possibly tag/branch it for others to clone if they want to use it in the future - then remove ProtoGen in favour of the C++ version?

**Comment by jtattermusch** [comment]
Yes, I think that's correct. I don't think we can afford to just kill the old ProtoGen. We should give users some time to migrate to the new protogen (they should be happy about that, because using it will be much simpler). We also want them to have access to the old ProtoGen as a backup solution in case some scenarios break with the new C++ protogen.

**Comment by jtattermusch** [comment]
I've done the history rewriting I wanted and the current state of this PR should represent the history with github users properly linked to the commits and some of the oldest commits removed.

**Comment by jtattermusch** [comment]
@csharptest ,
C# now uses many more codegen options (they now live in CsharpOptions.proto) than the other protobuf languages and we need to restrict the number of them to avoid pollution of the central descriptor.proto. We are hoping to cut down the number to max 3 or 4.

We've put together suggestions what can be done, can you please comment on this?

csharp_file_options.namespace -> becomes csharp_namespace (similarly, java uses java_namespace). Might also be removed and just use the package.

Umbrella classname (java has java_outer_classname) -> we can remove this one (it defaults to proto file name with Proto suffix) and reintroduce if we find out we need it.

CsharpFieldOptions.property_name -> becomes csharp_property_name in field options. Very useful for disambiguation

Options remove:
Public classes ->will default to true
Multiple files -> would be nice to have, but not currently implemented anyway
Code contracts 
Expand namespace directories -> we can reintroduce this one if needed.
CLS compliance
Generate private constructor (not sure why this is here, to be honest...)
File extension
Output directory (would be a protogen option)
Ignore Google protobuf
Compiler generated (we should probably just always do this)

Unsure about these ones:
Nest classes
Add serializable
Service generator type - suspect it can go with the new service work, but check (our current plan was to keep things simple and just remove service support and let users use the old ProtoGen for a while. We can add the service support back if it turns out it has active users).
CsharpServiceOptions.interface_id - not sure what this is for
CsharpMethodOptions.dispatch_id - not sure what this is for

**Comment by csharptest** [comment]
> > We are hoping to cut down the number to max 3 or 4.

Good :)

> > csharp_file_options.namespace -> becomes csharp_namespace (similarly,
> > java uses java_namespace). Might also be removed and just use the package.

We do use this rather heavily to ensure that the source generated takes the
same namespace as the project in Visual Studio.

> > Umbrella classname (java has java_outer_classname) -> we can remove this
> > one (it defaults to proto file name with Proto suffix) and reintroduce if
> > we find out we need it.

We actually don't use this, rather we use "umbrella_namespace" to namespace
off all the generated "noise" into a child namespace of the generating
source file.  Thus we set this to "Generated" so as MyFile.proto generates
to namespace "MyFile", the umbrella class goes into the namespace
"MyFile.Generated".

> > CsharpFieldOptions.property_name -> becomes csharp_property_name in
> > field options. Very useful for disambiguation

Agreed.

The following best summarizes their use and if they can be removed (at
least as far as I'm concerned)...  I've indicated a "how strong" do I
desire functionality in the form of "*Desired#00" where 00 is a number
between 1 and 10, 10 being the strongest.  Additionally they are listed in
order of importance.

==== _KEEPERS *====
-_service_generator_type_=[IRPCDISPATCH] *Desired#10 -- see REMARKS below.
-_cls_compliance_=[Bool] *Desired#9 - Without this the code may not compile
in some configurations/environments.
-_file_extension_=[String] *Desired#6 - (possible move to protoc) -- see
REMARKS below.
-_umbrella_namespace_=[String] *Desired#5 - Described above to put
generated code in a child namespace.
-_namespace_=[String] *Desired#4 - Required to sync namespace with Visual
Studio project settings
-_add_serializable*=[Bool] *Desired#3 - Default FALSE, *Required for cross
domain calls, but only supported in full/client framework.

==== _REMOVE? *====
-_umbrella_classname_=[String] *REMOVE - Can default to {FILE}Proto as
described above
-_public_classes_=[Bool] *REMOVE - Default to TRUE
-_multiple_files_=[Bool] *REMOVE - Default to FALSE
-_nest_classes_=[Bool] *REMOVE - Default to FALSE
-_code_contracts_=[Bool] *REMOVE - Default to FALSE
-_expand_namespace_directories_=[Bool] *REMOVE - Default to FALSE
-_output_directory_=[String] *Can default to original file location, but it
is nice to be explicit
-_ignore_google_protobuf_=[Bool] *REMOVE - Default to TRUE
-_line_break_=[Windows|Unix|Default] *REMOVE - Default to PLATFORM not UNIX
-_generate_private_ctor*=[Bool] *REMOVE - Default to FALSE

==== _REMARKS *====
-_file_extension*
Visual Studio handles auto-generated files differently and works best when
these generated files are suffixed ".Designer.cs" rather than just ".cs".
We interally use ".Generated.cs" to exclude from version control and/or
know why the file is changing when reviewing changeset.

-_generate_private_ctor_
This allows users to mixin (partial) a custom default constructor for the
message.  It is also desired that the generated ctor Builder(Message)
should be public by default so that object initializers can be used on a
builder for an existing message.

-_service_generator_type_

> > suspect it can go with the new service work, but check (our current plan
> > was to keep things simple and just remove service support and let users use
> > the old ProtoGen for a while. We can add the service support back if it
> > turns out it has active users).

Protocol Buffers primary use is to define wire protocols and it is very
good at that.  I make extensive use of the services (over 90% of my uses
for protobuf) and have several open source projects that rely on the
behavior of service_generator_type=IRPCDISPATCH.  There is a lot of
boiler-plate code that helps efficiently invoke interface methods based on
method name and inversly turns an interface method call into a method name
and argument in a common call. (see src\ProtocolBuffers\IRpcDispatch.cs)
 These two interfaces (IRpcServerStub/IRpcDispatch) and the associated code
generated makes it possible to write generic wrappers for transport layers
to tunnel proto based RPC.

While I can't expect Google to bow to my every whim, I can't express how
important this feature has become since it was introduced.  If you would
like to discuss over skype or cell let me know and I'd be glad to explain
why this is my #1 priority to keep working.  In the same breath I
understand v3 has undergone a singnificant amout of rework and I can
understand if services are being entirely removed from the project (however
unfortunate that might be to me personally).

-_CsharpServiceOptions.interface_id_ - Specifies the
System.Runtime.InteropServices.GuidAttribute attribute for the service
interface generated.  This is used to provide a reliable response from
System.Runtime.InteropServices.Marshal.GenerateGuidForType.  If
service_generator_type=[IRPCDISPATCH] goes away this is no longer needed,
if it remains, it would be nice to keep.

-_CsharpMethodOptions.dispatch_id_ - Specifies the
System.Runtime.InteropServices.DispIdAttribute attribute for the methods in
a service.  This can be used to avoid passing names of methods around since
Google Protocol Buffers lacks a numeric identity for the service method,
this custom attribute was used.  If service_generator_type=[IRPCDISPATCH]
goes away this is no longer needed, if it remains, it would be nice to keep.

==== _COMMAND LINE_ ====
On a final note, all of these are currently modifiable by providing
command-line options to ProtoGen.exe.  The reason for this is to perform
Visual Studio integration as a custom tool that follows the conventions set
forth by Microsoft.  Most important (for those options that remain) are
Input/Output directories and File Extension related settings.  Additionally
having the namespaces and cls_compliance allows us to reuse some protos
between projects without the need to copy/paste/edit.

Do you know if there is any plans to control these settings from the protoc
command-line?

-- Roger

**Comment by jtattermusch** [comment]
Thanks for great comments, Roger!

So the way I currently see is we should start with this initial set:
csharp_namespace
csharp_property_name
csharp_umbrella_namespace (frankly, I think the name of this one is pretty
unclear - btw, do I understand correctly that umbrella namespace only wraps
the SomeFileProto class and not the message classes themselves?)

The exact impact of changing umbrella_namespace and umbrella_classname is
still a bit foggy to me, so I have to read a bit more on that. But my
expectation is we might be fine with just using one of them.

COMMAND LINE OPTIONS
yes, you can actually set the options on command line on per-plugin basis
(an example would be dllexport_decl option for C++ protoc plugin: "protoc
--cpp_out=dllexport_decl=FOO_EXPORT:outdir foo.proto" - the way you specify
them is a little obscure, but I guess it should be fine). So, to limit our
impact on descriptor.proto, I think we could provide some of the options
only through commandline - expecially those that could break someone's
build but are not used very often or those that are not absolutely
necessary, but improve the development experience. To me, its these:

cls_compliance
file_extension

So you would go like "protoc
--csharp_out=cls_compliance=false:your/output/dir" or perhaps "protoc
--csharp_out=no_cls_compliance:file_extension=.Generated.cs":your/output/dir".

would that suffice?

SERVICES
ok, this is the tough part. I read some more documentation at looked at
what other languages are doing - and the problem is that services support
for all the other languages is deprecated. The recommended approach now is
that for each service type, you write a separate protoc plugin (that can
make use of the insertion points in the code generated by the in the
language-specific protoc plugin) to generate your service stub. This is
also what we are doing for gRPC service stub. The code is not so
complicated, as you can see here:
https://github.com/grpc/grpc/tree/master/src/compiler. And the entire
concept actually seems much cleaner to me than having several builtin
service generators in a single protoc plugin. So, the ideal approach to me
would be implementing the IRpcDispatch C# plugin as a separate plugin
(written in C++ and perhaps maintained as a separate project). With some
care, the generated service code could look 100% the same and would be
placed in exactly the same spot as it is now (we could use an insertion
point). Would that be a solution for you?

Btw, did you take a look at gRPC ("high performance, open source, general
RPC framework on top of HTTP/2")?
http://grpc.io/
https://github.com/grpc/grpc
It has many cool features and perhaps you could replace some IRpcDispatch
services you are using with gRPC. Work on gRPC C# is in progress (I am
actually developing it). We are hoping alpha version will be available soon.

**Comment by csharptest** [comment]
PSB...

On Fri, Apr 3, 2015 at 11:40 AM, Jan Tattermusch notifications@github.com
wrote:

> Thanks for great comments, Roger!
> 
> So the way I currently see is we should start with this initial set:
> csharp_namespace
> csharp_property_name
> csharp_umbrella_namespace (frankly, I think the name of this one is pretty
> unclear - btw, do I understand correctly that umbrella namespace only wraps
> the SomeFileProto class and not the message classes themselves?)

[ROK] Correct, it places the SomeFileProto class into a child namespace
like:

namespace SomePackage {
  namespace Proto {
     class SomFileProto { ... }
  }
  class SomeMessage { ... }
}

This means that my context-sensitive menu is not cluttered with junk
artifacts from the generation.  It also does a better job (IMHO) of
preventing name collisions with messages.  We currently default this to
"Proto" when a collision is detected between an umbrella class and a
message/service/enum.  see
\src\ProtocolBuffers\Descriptors\FileDescriptor.cs(164).

> The exact impact of changing umbrella_namespace and umbrella_classname is
> still a bit foggy to me, so I have to read a bit more on that. But my
> expectation is we might be fine with just using one of them.

[ROK] If I had to pick between the two, I'd rather see
csharp_umbrella_namespace than umbrella_classname.

> COMMAND LINE OPTIONS
> yes, you can actually set the options on command line on per-plugin basis
> (an example would be dllexport_decl option for C++ protoc plugin: "protoc
> --cpp_out=dllexport_decl=FOO_EXPORT:outdir foo.proto" - the way you specify
> them is a little obscure, but I guess it should be fine). So, to limit our
> impact on descriptor.proto, I think we could provide some of the options
> only through commandline - expecially those that could break someone's
> build but are not used very often or those that are not absolutely
> necessary, but improve the development experience. To me, its these:
> 
> cls_compliance
> file_extension
> 
> So you would go like "protoc
> --csharp_out=cls_compliance=false:your/output/dir" or perhaps "protoc
> 
> --csharp_out=no_cls_compliance:file_extension=.Generated.cs":your/output/dir".
> 
> would that suffice?

[ROK] Works for me, I'm not particular about the format.

> SERVICES
> ok, this is the tough part. I read some more documentation at looked at
> what other languages are doing - and the problem is that services support
> for all the other languages is deprecated. The recommended approach now is
> that for each service type, you write a separate protoc plugin (that can
> make use of the insertion points in the code generated by the in the
> language-specific protoc plugin) to generate your service stub. This is
> also what we are doing for gRPC service stub. The code is not so
> complicated, as you can see here:
> https://github.com/grpc/grpc/tree/master/src/compiler. And the entire
> concept actually seems much cleaner to me than having several builtin
> service generators in a single protoc plugin. So, the ideal approach to me
> would be implementing the IRpcDispatch C# plugin as a separate plugin
> (written in C++ and perhaps maintained as a separate project). With some
> care, the generated service code could look 100% the same and would be
> placed in exactly the same spot as it is now (we could use an insertion
> point). Would that be a solution for you?

[ROK] Sounds very reasonable, although I'm not sure how hard that is to
pull off.

> Btw, did you take a look at gRPC ("high performance, open source, general
> RPC framework on top of HTTP/2")?
> http://grpc.io/
> https://github.com/grpc/grpc
> It has many cool features and perhaps you could replace some IRpcDispatch
> services you are using with gRPC. Work on gRPC C# is in progress (I am
> actually developing it). We are hoping alpha version will be available
> soon.
> 
> [ROK] Yes, I've been following it a bit, very exciting work.  Still there
> are situations where more native control of the transport is desirable.
> For instance (protobuf-csharp-rpc) is wrapper on raw Win32 RPC channels
> that support authentication, encryption, and impersonation while still
> being amazingly fast and very reliable.  Not something I would expect to
> find in gRPC :)  We do however have several wrappers that support full HTTP
> REST services to be spec'd and implemented entirely in protobuf (
> http://csharptest.net/1062/build-a-rest-service-protocol-buffers-xml-json-using-protobuf-csharp-port/).
> I can easily see this type of work being replaced with gRPC at some point.

Anyway, so long as there is a way to get the code generated it's all good.
I assume the interfaces will be relocated as well then?

-- Roger

**Comment by jtattermusch** [comment]
please see inline

On Fri, Apr 3, 2015 at 10:37 AM, Roger Knapp notifications@github.com
wrote:

> PSB...
> 
> On Fri, Apr 3, 2015 at 11:40 AM, Jan Tattermusch <notifications@github.com
> 
> > wrote:
> > 
> > Thanks for great comments, Roger!
> > 
> > So the way I currently see is we should start with this initial set:
> > csharp_namespace
> > csharp_property_name
> > csharp_umbrella_namespace (frankly, I think the name of this one is
> > pretty
> > unclear - btw, do I understand correctly that umbrella namespace only
> > wraps
> > the SomeFileProto class and not the message classes themselves?)
> 
> [ROK] Correct, it places the SomeFileProto class into a child namespace
> like:
> 
> namespace SomePackage {
> namespace Proto {
> class SomFileProto { ... }
> }
> class SomeMessage { ... }
> }
> 
> This means that my context-sensitive menu is not cluttered with junk
> artifacts from the generation. It also does a better job (IMHO) of
> preventing name collisions with messages. We currently default this to
> "Proto" when a collision is detected between an umbrella class and a
> message/service/enum. see
> \src\ProtocolBuffers\Descriptors\FileDescriptor.cs(164).
> 
> > The exact impact of changing umbrella_namespace and umbrella_classname is
> > still a bit foggy to me, so I have to read a bit more on that. But my
> > expectation is we might be fine with just using one of them.
> 
> [ROK] If I had to pick between the two, I'd rather see
> csharp_umbrella_namespace than umbrella_classname.
> 
> > COMMAND LINE OPTIONS
> > yes, you can actually set the options on command line on per-plugin basis
> > (an example would be dllexport_decl option for C++ protoc plugin: "protoc
> > --cpp_out=dllexport_decl=FOO_EXPORT:outdir foo.proto" - the way you
> > specify
> > them is a little obscure, but I guess it should be fine). So, to limit
> > our
> > impact on descriptor.proto, I think we could provide some of the options
> > only through commandline - expecially those that could break someone's
> > build but are not used very often or those that are not absolutely
> > necessary, but improve the development experience. To me, its these:
> > 
> > cls_compliance
> > file_extension
> > 
> > So you would go like "protoc
> > --csharp_out=cls_compliance=false:your/output/dir" or perhaps "protoc
> > 
> > --csharp_out=no_cls_compliance:file_extension=.Generated.cs":your/output/dir".
> > 
> > would that suffice?
> 
> [ROK] Works for me, I'm not particular about the format.
> 
> > SERVICES
> > ok, this is the tough part. I read some more documentation at looked at
> > what other languages are doing - and the problem is that services support
> > for all the other languages is deprecated. The recommended approach now
> > is
> > that for each service type, you write a separate protoc plugin (that can
> > make use of the insertion points in the code generated by the in the
> > language-specific protoc plugin) to generate your service stub. This is
> > also what we are doing for gRPC service stub. The code is not so
> > complicated, as you can see here:
> > https://github.com/grpc/grpc/tree/master/src/compiler. And the entire
> > concept actually seems much cleaner to me than having several builtin
> > service generators in a single protoc plugin. So, the ideal approach to
> > me
> > would be implementing the IRpcDispatch C# plugin as a separate plugin
> > (written in C++ and perhaps maintained as a separate project). With some
> > care, the generated service code could look 100% the same and would be
> > placed in exactly the same spot as it is now (we could use an insertion
> > point). Would that be a solution for you?
> 
> [ROK] Sounds very reasonable, although I'm not sure how hard that is to
> pull off.

Implementation-wise, I would say it's pretty easy (see grpc plugins, they
are not very esoteric, Java gRPC stub generator
https://github.com/grpc/grpc-java/blob/master/compiler/src/java_plugin/cpp/java_generator.cpp
is about 700 lines of code).
The needed know how should be quite easy to obtain once we implement protoc
plugin for gRPC C# (because this is essentially going to do the same thing
- so you can be heavily inspired).
  There is some overhead associated with starting a new github project to
  give the IRpcDispatch protoc plugin a place to live (I suppose that project
  would be owned by you), but on the other hand, the resulting protoc plugin
  for IRpcDispatch would be probably easier to use than then the current
  ProtoGen.exe (that is a little bit esoteric and also needs to reimplement
  some protoc concepts that you get for free once you write the plugin in
  C++).

Until a separate plugin for IRpcDispatch stubs would exist, everyone could
use the old version of ProtoGen.exe (we are planning to dump the code from
current google code repo to a github repo to provide place from where you
can clone the original code and possibly make a github fork of the repo).

> > Btw, did you take a look at gRPC ("high performance, open source, general
> > RPC framework on top of HTTP/2")?
> > http://grpc.io/
> > https://github.com/grpc/grpc
> > It has many cool features and perhaps you could replace some IRpcDispatch
> > services you are using with gRPC. Work on gRPC C# is in progress (I am
> > actually developing it). We are hoping alpha version will be available
> > soon.
> > 
> > [ROK] Yes, I've been following it a bit, very exciting work. Still there
> > are situations where more native control of the transport is desirable.
> > For instance (protobuf-csharp-rpc) is wrapper on raw Win32 RPC channels
> > that support authentication, encryption, and impersonation while still
> > being amazingly fast and very reliable. Not something I would expect to
> > find in gRPC :) We do however have several wrappers that support full HTTP
> > REST services to be spec'd and implemented entirely in protobuf (
> 
> http://csharptest.net/1062/build-a-rest-service-protocol-buffers-xml-json-using-protobuf-csharp-port/
> ).
> I can easily see this type of work being replaced with gRPC at some point.

Sounds good. Btw, feedback on gRPC C# API and general usability of the
library is very welcome.

> Anyway, so long as there is a way to get the code generated it's all good.
> I assume the interfaces will be relocated as well then?

I am fine for the IRpcDispatch interfaces to remain in the main
ProtocolBuffers assembly for as long as needed. I don't think they are
going to bother anyone and we want to keep things simple when doing the
migration.

**Comment by jskeet** [comment]
One quick comment on a small part of an earlier response:

> _generate_private_ctor_  
> This allows users to mixin (partial) a custom default constructor for the
> message. It is also desired that the generated ctor Builder(Message)
> should be public by default so that object initializers can be used on a
> builder for an existing message.

The first part could be better addressed by making the private constructor call a partial method - then if you want to specify your own constructor body, you can just implement the partial method in a partial class. I'd expect that to work for most cases. Any thoughts about where it wouldn't? (Yes, this would require a change in the codegen to declare and call the partial method, and then a change in anything which used to use the flag to do custom code in constructors - but it shouldn't be too bad.)

I agree that the generated constructor for a builder should be public, but that sounds like a different matter.

**Comment by jtattermusch** [comment]
I think this pull request is ready to be merged. 
-- All the contributors of the old project should be now correctly linked to their github accounts. All of them have signed the CLA and they agree with pulling their code under google/protobuf.
-- I removed binary files from csharp/lib and put a README.md with instructions how to obtain the dependencies
-- please review last couple of commits (starting from e77878e) where I did the necessary cleanup and wrote up some explanation.
-- I've tried to build it on windows and all the tests passed.

**Comment by jskeet** [comment]
LGTM. Let's chat by email about how exactly we want to manage branches etc to get code into the Google repo. I'm happy for you to merge this into your reviewed branch. I'm sure we'll want to prune more stuff, but it's good to see the binaries go to start with.

**Pull request merged**
