### PR TITLE
Add System.Memory dependency

### PR DESCRIPTION
**Pull request by jtattermusch**
- unfortunately System.Memory that doesn't support netstandard1.0, so we need to require netstandard1.1
but based on https://docs.microsoft.com/en-us/dotnet/standard/net-standard (and http://immo.landwerth.net/netstandard-versions/#)  the only difference in supported plaforms between netstandard1.0 and netstandard1.1  is that netstandard1.1. doesn't work on Windows Phone Silverlight (but silverlight seems to be deprecated).

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @mkosieradzki

**Comment by jtattermusch** [comment]
getting this error so far: https://stackoverflow.com/questions/45282478/memorystream-does-not-contain-a-definition-for-getbuffer

**Comment by mkosieradzki** [comment]
You need to change #if NETSTANDARD1_0 to #if NETSTANDARD1_1

**Comment by jtattermusch** [comment]
@mkosieradzki  good point, thanks!

**Comment by mkosieradzki** [comment]
This PR was wrong as well. You forgot to add netstandard1.1 to unconditional TargetFrameworks. I have fixed this in #8

**Comment by jtattermusch** [comment]
@mkosieradzki  thanks for pointing that out. This should be fixed in a separate PR. Done so in #9 .

**Pull request merged**
